### ISSUE TITLE
Link back to this repo from Docker Hub page

### ISSUE THREAD

**Issue by i-ky** [ohbarye/swagger-merger-docker#2]
At the moment [Docker Hub page](https://hub.docker.com/r/ohbarye/swagger-merger) only links to [`swagger-merger` repo](https://github.com/WindomZ/swagger-merger), which is nice, but it should also link to this repo, because this is where image source code is located. Image-related issues and pull requests need to be submitted here.

**Comment by ohbarye** [comment]
I updated the Docker Hub page, thank you.

<img width="648" alt="image" src="https://github.com/ohbarye/swagger-merger-docker/assets/1811616/166c229c-360d-422f-bd69-87e5a89f135a">
