### ISSUE TITLE
Update the image on Docker Hub

### ISSUE THREAD

**Issue by i-ky** [ohbarye/swagger-merger-docker#4]
The version of `swagger-merger` in the image is 1.4.3:
```
$ docker run --rm --entrypoint swagger-merger ohbarye/swagger-merger --version
1.4.3
```
The latest version of `swagger-merger` [in NPM](https://www.npmjs.com/package/swagger-merger?activeTab=versions) is 1.5.4.

Could you please update the image?

**Comment by ohbarye** [comment]
Thanks for your suggestion. I pushed the image as v0.1.2 including swagger-merger v1.5.4.

https://hub.docker.com/layers/ohbarye/swagger-merger/0.1.2/images/sha256-bad3bb1cbeb7f7751dae26a364a26ee7b9af9ac671e4449154a70e2e3fc167bc?context=repo

**Comment by i-ky** [comment]
I am getting:
```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```
I think this is due to new images being for `linux/arm64/v8` platform instead of `linux/amd64`.

Would it be possible to publish images for `linux/amd64` as well?
